### ISSUE TITLE
Ethereum Name Service

### ISSUE THREAD

**Issue by joschicif** [cifunibas/cifBlockchainMarketStudy#74]

**Comment by jadster** [comment]
Cool project.
related:
https://medium.com/@jgm.orinoco/domainsale-an-on-chain-secondary-ens-market-b3330f6e5dda

**Comment by jadster** [comment]
Developers (e.g. lead dev Nick Johnson) are super-responsive on gitter chat.
https://gitter.im/ethereum/go-ethereum/name-registry

Also:
https://ens.domains/hack2018/
